name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.4'
            dependencies: 'highest'

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_sqlite
        ini-values: zend.assertions=1
        coverage: none

    - name: Composer install
      uses: ramsey/composer-install@v3
      with:
        dependency-versions: ${{ matrix.dependencies }}
        composer-options: ${{ matrix.composer-options }}

    - name: Composer post install
      run: composer run-script post-install-cmd --no-interaction

    - name: Run PHPUnit
      run: vendor/bin/phpunit
      env:
        DATABASE_TEST_URL: sqlite://./testdb.sqlite

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, intl
        coverage: none
        tools: cs2pr

    - name: Composer install
      uses: ramsey/composer-install@v3

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs --report=checkstyle | cs2pr
